[package]
name = "call_lib"
version = "0.1.0"
authors = ["pzhuang"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ppm = { path = "../libppm"}