[package]
name = "ppm-esgi-zpl"
version = "0.1.0"
authors = ["Luis Valdez <luis.valdez@affluences.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
